### ISSUE TITLE
不能正常运行

### ISSUE THREAD

**Issue by xiangpaopao** [BYVoid/microblog#5]
在终端 node app.js后
浏览器中访问，显示：
Express
500 SyntaxError: Unexpected token ILLEGAL
at Object.Function (unknown source)
at Object.exports.compile (/Users/xiangpaopao/workspace/node/microblog/node_modules/ejs/lib/ejs.js:83:12)
at Function.exports.compile (/Users/xiangpaopao/workspace/node/microblog/node_modules/express/lib/view.js:68:33)
at ServerResponse.res._render (/Users/xiangpaopao/workspace/node/microblog/node_modules/express/lib/view.js:417:18)
at ServerResponse.res.render (/Users/xiangpaopao/workspace/node/microblog/node_modules/express/lib/view.js:318:17)
at module.exports.app.get.res.render.title (/Users/xiangpaopao/workspace/node/microblog/routes/index.js:11:11)
at Post.get (/Users/xiangpaopao/workspace/node/microblog/models/post.js:69:9)
at Cursor.toArray (/Users/xiangpaopao/workspace/node/microblog/node_modules/mongodb/lib/mongodb/cursor.js:131:9)
at Cursor.each (/Users/xiangpaopao/workspace/node/microblog/node_modules/mongodb/lib/mongodb/cursor.js:173:11)
at Cursor.nextObject (/Users/xiangpaopao/workspace/node/microblog/node_modules/mongodb/lib/mongodb/cursor.js:454:35)

请问是我配置的问题吗

**Comment by BYVoid** [comment]
npm install -g continuation
npm test

**Comment by xiangpaopao** [comment]
谢谢，不过还是没成功，今天刚开始学node，我再试试

**Comment by yuanjianhang** [comment]
不能按照教程上的来了，你可以去看下express的更新日志，新的版本更改了好多东西。BYWoid的这个项目太老了。

**Comment by skorotkiewicz** [comment]
I have the same problem.

I have already installed:
npm install -g continuation

but the problem still occurs

**Comment by wzhscript** [comment]
我也遇到了相同的问题。。。

**Comment by xiangpaopao** [comment]
那个教程中的东西比较古老了，貌似这个demo网上有流传的其他版本 试试这个https://github.com/PaladinTyrion/nodejs_BYVoid_demo

**Comment by jackchoumine** [comment]
请教一个问题，我安装了insight.io来阅读gihub上的项目，有的项目不能用这个插件，显示 insight not included yet，这是仓库的问题还是因为其它啊？ 我发现几个含有中文的项目都不能用，这是因为项目中含有中文？
